FROM php:8.4-fpm-alpine

ARG UID=1000
ARG GID=1000

RUN apk add --no-cache git bash curl unzip libpng-dev libxml2-dev oniguruma-dev nodejs npm

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd opcache

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

# Non-root user
RUN addgroup -g ${GID} -S rabetxrpflow \
    && adduser -u ${UID} -G rabetxrpflow -S rabetxrpflow

USER rabetxrpflow

CMD ["php-fpm"]
