FROM php:8.4-fpm-alpine

ARG UID=1001
ARG GID=1001

RUN apk add --no-cache \
    bash \
    git \
    libpng-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
    freetype-dev \
    libxml2-dev \
    oniguruma-dev \
    icu-dev \
    zlib-dev \
    zip \
    unzip \
    mysql-client \
    && docker-php-ext-install pdo_mysql mbstring bcmath exif pcntl gd intl opcache

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

# Non-root user
RUN addgroup -g ${GID} -S rabetxrpflow \
    && adduser -u ${UID} -G rabetxrpflow -S rabetxrpflow

USER rabetxrpflow

CMD ["php-fpm"]
